name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    name: Simple Deployment Pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Npm install
        run: npm install
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start
          wait-on: http://localhost:3001
      - name: Deploy
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message), '#skip') == false }}
        uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: taukopaikat-mono 
          heroku_email: "jirka.hartonen@gmail.com"
          healthcheck: "https://taukopaikat-mono.herokuapp.com"          
          rollbackonhealthcheckfailed: true