name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    name: Simple Deployment Pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Npm install
        run: npm install
      - name: Lint
        run: npm run eslint 